### ISSUE TITLE
Make changes according to General Feedback

### ISSUE THREAD

**Issue by rohit-vishwakarma** [rohit-vishwakarma/scribble#143]
Sub-issues:

- [x] Fix articles tests
- [x] Fix add category of manage categories settings
- [x] Use article id for admin routes
- [x] Generate Slug after the first time publishing an article
- [x] Add validation to article title
- [x] Add placeholder to article search bar
- [x] Fix SiteLogin rendering after logged in to EUI
- [x] Use query params for settings
- [x] Remove icon from Add new article button
- [x] Fix all loading state 
- [x] Fix controller exception messages
- [x] Fix Edge cases of Article form
- [x] Use Partial in Jbuilder
- [x] Move Functionality from application controller to concerns
- [x] Fix tests according to Expectation vs Reality
- [x] Add tests for category position update
- [x] Use Promise.all for multiple promises
- [x] Rename Site Model to Organization Model and make necessary changes
- [x] Add is_password_protected to organizations table and make necessary changes
- [x] Add associations to organization model and make necessary changes
- [x] Fix Articles filter
- [x] Fix Redirection edge cases and add tests for it
- [x] Fix Manage categories Delete action
- [x] Use Memoization for Current User
- [x] Fix articles table to redirect published article to EUi
