### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by rohit-vishwakarma** [rohit-vishwakarma/scribble#57]
sub-issues
- [x] Add tests for article model.
- [x] Add tests for category model.
- [x] Add tests for user model.
- [x] Add tests for article controller.
- [x] Add tests for category controller.
- [x] Add tests for site model.
- [x] Add tests for sites controller.
- [x] Add tests for redirection model.
- [x] Add tests for redirections controller.
