### ISSUE TITLE
Create EUI

### ISSUE THREAD

**Issue by rohit-vishwakarma** [rohit-vishwakarma/scribble#79]
Sub-issues:

- [x] EUI: Frontend - Add logic to route to EUI
- [x] EUI: Frontend & Backend - Add Login page to EUI
- [x] EUI: Frontend & Backend - Add a left sidebar to list categories and articles
- [x] EUI: Frontend & Backend - Add a component to display the preview of the article
